- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Show var content
      debug:
        msg: "question 01 answer: {{ test_answer_01 }}"
